### PR TITLE
Minor wording and spelling adjustments.

### PR DESCRIPTION
**Pull request by in3rsha**
I think you've written a great tutorial. Nice work.

I made some minor changes to the wording as I was reading through. Hope you don't mind.

### CODE REVIEW

**Comment by geraldb** [comment]
@in3rsha Thanks for the fixes. Thanks for the Learn me a Bitcoin site and the source code samples! A great inspiration and I'm still learning and reading (more of your Learn me a Bitcoin) pages. Keep it up. Cheers. Prost.

**Comment by in3rsha** [comment]
My pleasure. Keep up the good work yourself too, I enjoy your writing and coding style.

One question if you don't mind me asking: what's the reason behind positioning the "**BEWARE**" warning at the top of the guide? Your article is so good I would like to be able dive straight in to it.

**Comment by geraldb** [comment]
About the "BEWARE" - The other inspiration / source is the "Programming Bitcoin from Scratch" book. The author Jimmy Song is clearly a Bitcoin maximalist.  I am the opposite - a no coiner and bitcoin "minimalist". Sorry I strongly believe that the insane waste of the mining (and the CO2 emissions) must be stopped and, thus, this "little public awareness campaign".  See <https://digiconomist.net/bitcoin-energy-consumption> for background.  The get-rich-quick greed fest is another story. That's just human nature they best we can do is make fun of it as Tr0llyTr0llFace <https://twitter.com/Tr0llyTr0llFace> says: "I said Bitcoin is a Ponzi scheme before it was cool. Buying magical virtual coins from mysterious people on the Internet will not make you rich."

Anyways, thanks again for your great Learn me a Bitcoin site (and code samples). The details are just amazing and you are really making it fun (Learn me a- style) with your illustrations.  Cheers. Prost. Greetings from Vienna (Home of the School of Austrian Economics :-).

**Comment by in3rsha** [comment]
Thank you for the explanation. I understand.

Do you use IRC or something similar? (If you don't mind me asking)

**Comment by geraldb** [comment]
No worries. Sorry I don't use any IRC. Keep up the great work on Learn me a Bitcoin. Cheers. Prost.

**Pull request merged**
